server:
  port: 8000
spring:
  application:
    name: kitty-monitor
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# \u6CE8\u518C\u5230consul\u7684\u670D\u52A1\u540D\u79F0


